### ISSUE TITLE
вопрос по использованиюю. 

### ISSUE THREAD

**Issue by RexSatanas** [GhostRooter0953/discord-ips-kvas-adder#1]
нужно ли что-то еще делать после запуска скрипта и подверждения. поставил обновление на midnight. я так понимаю ip обновятся в полночь и дис должен заработать? так же вопрос с shadowsocs работает?

**Comment by wildrun0** [comment]
++, тоже запустил файл, сделал выполнение задачи на ребут. А как проверить работоспособность то?) rtc не поднимается, другие домены в квасе и так добавлены мною вручную

**Comment by GhostRooter0953** [comment]
> нужно ли что-то еще делать после запуска скрипта и подверждения. поставил обновление на midnight. я так понимаю ip обновятся в полночь и дис должен заработать? так же вопрос с shadowsocs работает?

Родительская репо подразумевает, что скрипт `ipset-adder.sh` будет запущен вручную. То-есть, необходимо зайти в дир репо и запустить скрипт в интерактиве либо на автомате (_учитывая этот [пункт](https://github.com/GhostRooter0953/discord-voice-ips#:~:text=%D1%83%D0%BC%D0%BE%D0%BB%D1%87%D0%B0%D0%BD%D0%B8%D1%8E%20%D1%81%D0%BF%D0%B8%D1%81%D0%BE%D0%BA%20%D0%BD%D0%B0%D0%B7%D1%8B%D0%B2%D0%B0%D0%B5%D1%82%D1%81%D1%8F-,unblock,-%2C%20%D0%B5%D1%81%D0%BB%D0%B8%20%D1%83%20%D0%B2%D0%B0%D1%81)_). Текущий же скрипт больше нужен для обновления и придания автономности реализации с импортом списков.

> ++, тоже запустил файл, сделал выполнение задачи на ребут. А как проверить работоспособность то?) rtc не поднимается, другие домены в квасе и так добавлены мною вручную

1. Как называется список создаваемый KVAS-ом? Покажи вывод:

```
~# ipset list | grep Name | grep -vE '(NDM|UPNP)'
```

2. К каким гс подключаешься? В родительской репо по умолчанию только списки для RU-EU и бонусом Дубайск с Сингапуром.

**Comment by wildrun0** [comment]
> ipset list -n | grep -vE '(NDM|UPNP)'

выводит unblock



> 2\. К каким гс подключаешься? В родительской репо по умолчанию только списки для RU-EU и бонусом Дубайск с Сингапуром.

И к РУ сервакам, и к ЕУ - нигде не цепляется. Роутер перезагрузил (чтобы скрипт сработал) - все равно ничего.

**Comment by GhostRooter0953** [comment]
### В планах допилить следующее

- `ipset-adder.sh`: парсинг существующих списков на основе регулярки выше и предложение выбрать список, в который будет осуществляться импорт
- `kvas-ipset-adder.sh`: добавление возможности передать аргумент, который будет подставляться в крон задании в качестве аргумента для `ipset-adder.sh`:

```bash
SCRIPT_TO_RUN="ipset-adder.sh auto $1"
...
"0 0 * * * cd $EXTRACTED_DIR && /opt/bin/bash $SCRIPT_TO_RUN"
```

**Comment by GhostRooter0953** [comment]
> > ipset list -n | grep -vE '(NDM|UPNP)'
> 
> выводит unblock
> 
> > 2. К каким гс подключаешься? В родительской репо по умолчанию только списки для RU-EU и бонусом Дубайск с Сингапуром.
> 
> И к РУ сервакам, и к ЕУ - нигде не цепляется. Роутер перезагрузил (чтобы скрипт сработал) - все равно ничего.

Покажи вывод:
```
~# ipset list unblock | wc -l
```
и
```
~# kvas show | grep dis
```

**Comment by wildrun0** [comment]
> ipset list unblock | wc -l

157

> kvas show | grep dis

```
*discord.com
*discord.gg
*discord.media
*discordapp.com
*discordapp.net
cdn.discordapp.com
dis.gd
discord-attachments-uploads-prd.storage.googleapis.com
discord.co
discord.design
discord.dev
discord.gg
discord.gift
discord.gifts
discord.media
discord.new
discord.store
discord.tools
discordactivities.com
discordapp.com
discordapp.net
discordcdn.com
discordmerch.com
discordpartygames.com
discordsays.com
discordsez.com
discordstatus.com
gateway.discord.gg
images-ext-1.discordapp.net
media.discordapp.net
www.discord.app
www.discord.com
```

**Comment by GhostRooter0953** [comment]
> > kvas show | grep dis
> 
> ```
> *discord.com
> *discord.gg
> *discord.media
> *discordapp.com
> *discordapp.net
> cdn.discordapp.com
> dis.gd
> discord-attachments-uploads-prd.storage.googleapis.com
> discord.co
> discord.design
> discord.dev
> discord.gg
> discord.gift
> discord.gifts
> discord.media
> discord.new
> discord.store
> discord.tools
> discordactivities.com
> discordapp.com
> discordapp.net
> discordcdn.com
> discordmerch.com
> discordpartygames.com
> discordsays.com
> discordsez.com
> discordstatus.com
> gateway.discord.gg
> images-ext-1.discordapp.net
> media.discordapp.net
> www.discord.app
> www.discord.com
> ```

Выкини это и поменяй на это:

```
~# kvas show | grep dis
*dis.gd
*discord-activities.com
*discord.co
*discord.com
*discord.design
*discord.dev
*discord.gg
*discord.gift
*discord.gifts
*discord.media
*discord.new
*discord.store
*discord.tools
*discordactivities.com
*discordapp.com
*discordapp.net
*discordcdn.com
*discordmerch.com
*discordpartygames.com
*discordsays.com
*discordsez.com
*discordstatus.com
```

> > ipset list unblock | wc -l
> 
> 157
> 

Затем выполни:

```bash
cd </путь_до_discord-voice-ips>
./ipset-adder.sh auto
```

**Comment by wildrun0** [comment]
> cd </путь_до_discord-voice-ips>
> ./ipset-adder.sh auto


```
/opt/tmp/discord-voice-ips-light # ./ipset-adder.sh auto
Запущен режим 'auto'. Используем IPset список: 'unblock'
 - Генерируем IPset список из файла ./main_domains/discord-main-ip-list
 - Генерируем IPset список из файла ./voice_domains/discord-voice-ip-list
IPset список 'unblock' уже существует.
Загружено 1486 IP адреса(ов) в список 'unblock'.
```

Заработало!! :) Благодарю

Я не очень силен в нетворкинге, подскажите, у меня не работало из-за моего списка квас, из-за того что не те домены были добавлены?

**Comment by GhostRooter0953** [comment]
> > cd </путь_до_discord-voice-ips>
> > ./ipset-adder.sh auto
> 
> ```
> /opt/tmp/discord-voice-ips-light # ./ipset-adder.sh auto
> Запущен режим 'auto'. Используем IPset список: 'unblock'
>  - Генерируем IPset список из файла ./main_domains/discord-main-ip-list
>  - Генерируем IPset список из файла ./voice_domains/discord-voice-ip-list
> IPset список 'unblock' уже существует.
> Загружено 1486 IP адреса(ов) в список 'unblock'.
> ```
> 
> Заработало!! :) Благодарю
> 
> Я не очень силен в нетворкинге, подскажите, у меня не работало из-за моего списка квас, из-за того что не те домены были добавлены?

ГС не работали - 146% из-за того, что IP не были импортированы (_сужу по количеству, т.к. только на RU приходится 166 хоста_).
А домены, это так, на всякий.

**Comment by wildrun0** [comment]
> IP не были импортированы

А ведь и вправду, 1510 показывает теперь.
Получается задача в кроне не отрабатывает? Ставить не ребут а на полночь?

**Comment by wildrun0** [comment]
Вообще в идеале чтобы оно отрабатывало и на ребут, и на полночь)

**Comment by GhostRooter0953** [comment]
> Вообще в идеале чтобы оно отрабатывало и на ребут, и на полночь)

Такой вариант в скрипте предусмотрю. Как и проверку на отсутствие/наличие адресов из списков репо в списке IPset

**Comment by RexSatanas** [comment]
/opt/tmp/discord-voice-ips-light # ./ipset-adder.sh auto
-sh: ./ipset-adder.sh: not found
у меня вот так почему то. хотя файл точно етсь
<img width="635" alt="Снимок экрана 2024-10-20 в 18 29 40" src="https://github.com/user-attachments/assets/2c93c0fb-8141-4d71-803a-72bd2fe4e346">

**Comment by GhostRooter0953** [comment]
> /opt/tmp/discord-voice-ips-light # ./ipset-adder.sh auto -sh: ./ipset-adder.sh: not found у меня вот так почему то. хотя файл точно етсь <img alt="Снимок экрана 2024-10-20 в 18 29 40" width="635" src="https://private-user-images.githubusercontent.com/77634191/378201519-2c93c0fb-8141-4d71-803a-72bd2fe4e346.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDAxMDUsIm5iZiI6MTcyOTQzOTgwNSwicGF0aCI6Ii83NzYzNDE5MS8zNzgyMDE1MTktMmM5M2MwZmItODE0MS00ZDcxLTgwM2EtNzJiZDJmZTRlMzQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDE1NTY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3OTg4YjQ1YmYzYTdlMDlmMjg5MDAzNmFkY2RiOTQzZmI0MzhlMmM2ZDMwNGMwODdkZGRjYWE1MDQ1NDFmN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.H4rneJ6eEFlcYZOs25Y2DUK3HTo8Xn-w8GPzYkpglVQ">
> 
> а вот если через sh /opt/tmp/discord-voice-ips-light # sh ipset-adder.sh auto ipset-adder.sh: line 66: syntax error: unexpected redirection

Дай вывод:

```bash
~# which bash
```

**Comment by RexSatanas** [comment]
/opt/tmp/discord-voice-ips-light # ./ipset-adder.sh
Генерируем IPset списки...
Введите имя для IPset списка (он будет создан, если таковой отсутствует): discor        d
Используем IPset список: 'discord'
 - Генерируем IPset список из файла ./main_domains/discord-main-ip-list
 - Генерируем IPset список из файла ./voice_domains/discord-voice-ip-list
 - Генерируем IPset список из файла ./regions/bucharest/bucharest-voice-ip
 - Генерируем IPset список из файла ./regions/dubai/dubai-voice-ip
 - Генерируем IPset список из файла ./regions/finland/finland-voice-ip
 - Генерируем IPset список из файла ./regions/frankfurt/frankfurt-voice-ip
 - Генерируем IPset список из файла ./regions/madrid/madrid-voice-ip
 - Генерируем IPset список из файла ./regions/milan/milan-voice-ip
 - Генерируем IPset список из файла ./regions/rotterdam/rotterdam-voice-ip
 - Генерируем IPset список из файла ./regions/russia/russia-voice-ip
 - Генерируем IPset список из файла ./regions/singapore/singapore-voice-ip
 - Генерируем IPset список из файла ./regions/stockholm/stockholm-voice-ip
 - Генерируем IPset список из файла ./regions/warsaw/warsaw-voice-ip
IPset список 'discord' не найден. Создаем...
IPset список 'discord' создан.
Выберите списки для загрузки:
1. Список с основными серверами
2. Список с основными и всеми голосовыми серверами
3. Список с основными и конкретными голосовыми серверами по регионам
Введите номер варианта (1-3): 2
Загружено 1441 IP адреса(ов) в список 'discord'.
Все IPset списки сгенерированы и готовы к использованию.
вот вроде сгенерил  но все равно не подрубается войс. использую shadowsocs

**Comment by GhostRooter0953** [comment]
> /opt/tmp/discord-voice-ips-light # ./ipset-adder.sh auto Запущен режим 'auto'. Используем IPset список: 'unblock'
> 
> * Генерируем IPset список из файла ./main_domains/discord-main-ip-list
> * Генерируем IPset список из файла ./voice_domains/discord-voice-ip-list
>   IPset список 'unblock' уже существует.
>   Загружено 1441 IP адреса(ов) в список 'unblock'.
> 
> вот вроде сгенерил но все равно не подрубается войс. использую shadowsocs

Покажи вывод:
```
~# ipset list unblock | wc -l
```
и
```
~# kvas show | grep dis
```

**Comment by RexSatanas** [comment]
/opt/tmp/discord-voice-ips-light # ipset list unblock | wc -l
1153
/opt/tmp/discord-voice-ips-light # kvas show | grep dis
*dis.gd
*discord-activities.com
*discord.co
*discord.com
*discord.design
*discord.dev
*discord.gg
*discord.gift
*discord.gifts
*discord.media
*discord.new
*discord.store
*discord.tools
*discordactivities.com
*discordapp.com
*discordapp.io
*discordapp.net
*discordapp.org
*discordmerch.com
*discordpartygames.com
*discordsays.com
*discordstatus.com
*discours.io
*disctech.com
*gamedistribution.com
*redis.com
*redis.io
discord-attachments-uploads-prd.storage.googleapis.com
/opt/tmp/discord-voice-ips-light #

**Comment by GhostRooter0953** [comment]
Любопытно, как же так получается, что скрипт говорит:

```bash
Загружено 1441 IP адреса(ов) в список 'unblock'.
```
А у тебя в выводе:

```
/opt/tmp/discord-voice-ips-light # ipset list unblock | wc -l
1153
```

**Comment by GhostRooter0953** [comment]
> /opt/tmp/discord-voice-ips-light # ipset list unblock | wc -l 1153 /opt/tmp/discord-voice-ips-light # kvas show | grep dis *dis.gd *discord-activities.com *discord.co *discord.com *discord.design *discord.dev *discord.gg *discord.gift *discord.gifts *discord.media *discord.new *discord.store *discord.tools *discordactivities.com *discordapp.com *discordapp.io *discordapp.net *discordapp.org *discordmerch.com *discordpartygames.com *discordsays.com *discordstatus.com *discours.io *disctech.com *gamedistribution.com *redis.com *redis.io discord-attachments-uploads-prd.storage.googleapis.com /opt/tmp/discord-voice-ips-light #

Выполни `kvas reset`, а затем снова `./ipset-adder.sh auto`

**Comment by RexSatanas** [comment]
Переустановка iptables для shadowsocks завершена УСПЕШНО
Удаляем все ранее созданные таблицы для утилит ipУСПЕШНОp
Создаем все необходимые таблицы для утилит ipset УСПЕШНО
Очищаем все ранее созданные iptables правила для SHADOWОШИБКА
Создаем iptables правила для SHADOWSOCKS соединенУСПЕШНО
Заполняем ipset таблицу данными из списка разблокУСПЕШНО
Заполняем dnsmasq таблицу данными из списка разблУСПЕШНОи.
Создаем таблицу маршрутизации ID#1001 для 'shadowУСПЕШНО
Перезапускаем shadowsocks                        УСПЕШНО
Перезапускаем AdGuardHome                        УСПЕШНО
----------------------------------------------------------
/opt/tmp/discord-voice-ips-light # ./ipset-adder.sh auto
Запущен режим 'auto'. Используем IPset список: 'unblock'
 - Генерируем IPset список из файла ./main_domains/discord-main-ip-list
 - Генерируем IPset список из файла ./voice_domains/discord-voice-ip-list
IPset список 'unblock' уже существует.
Загружено 1441 IP адреса(ов) в список 'unblock'.
/opt/tmp/discord-voice-ips-light # ipset list unblock | wc -l
2588
/opt/tmp/discord-voice-ips-light #

походу не очищается iptables

**Comment by GhostRooter0953** [comment]
>   Загружено 1441 IP адреса(ов) в список 'unblock'.
>   /opt/tmp/discord-voice-ips-light # ipset list unblock | wc -l
>   2588
>   /opt/tmp/discord-voice-ips-light #

Нууу, теперь выглядит так, что всё ок.

> походу не очищается iptables

???
```bash
~# # iptables-save | grep unblock
```

**Comment by RexSatanas** [comment]
/opt/tmp/discord-voice-ips-light # iptables-save | grep unblock
-A PREROUTING -i br0 -p tcp -m set --match-set unblock dst -j REDIRECT --to-ports 1181
-A PREROUTING -i br0 -p udp -m set --match-set unblock dst -j REDIRECT --to-ports 1181
ни в какую. бесконечно пытается запрыгнкть в войс и вылетает с не установлен маршрут

**Comment by GhostRooter0953** [comment]
> /opt/tmp/discord-voice-ips-light # iptables-save | grep unblock -A PREROUTING -i br0 -p tcp -m set --match-set unblock dst -j REDIRECT --to-ports 1181 -A PREROUTING -i br0 -p udp -m set --match-set unblock dst -j REDIRECT --to-ports 1181 ни в какую. бесконечно пытается запрыгнкть в войс и вылетает с не установлен маршрут

Ага, вижу.
Рули себе VPN и жизнь наладится

**Comment by RexSatanas** [comment]
в каком плане рули себе vpn?

**Comment by GhostRooter0953** [comment]
> в каком плане рули себе vpn?

Вместо соксов.

**Comment by GhostRooter0953** [comment]
Полагаю, что суть проблемы в твоём сценарии, в UDP трафике

**Comment by RexSatanas** [comment]
Понял. Буду пробовать
