### ISSUE TITLE
После kvas add надо заново использовать ipset-adder

### ISSUE THREAD

**Issue by wildrun0** [GhostRooter0953/discord-ips-kvas-adder#2]
Проблема описана в заголовке, квас после добавления (и удаления?) домена обновляет ipset, что логично в принципе, и адреса дискордовские пропадают из таблицы. Это как-то можно пофиксить или это вынужденная мера с которой придется мириться?

**Comment by GhostRooter0953** [comment]
> Проблема описана в заголовке, квас после добавления (и удаления?) домена обновляет ipset, что логично в принципе, и адреса дискордовские пропадают из таблицы. Это как-то можно пофиксить или это вынужденная мера с которой придется мириться?

Квасовую портянку не ковырял и о такой ручке не в курсе.
Поэтому остаётся только что-то своё колхозить. Я пока до решения не добрался (временное - алиас команд из крона).
