### ISSUE TITLE
в ipset все адреса есть, но не подключается

### ISSUE THREAD

**Issue by mist4keXD** [GhostRooter0953/discord-ips-kvas-adder#3]
Здравствуйте! 
Сделал по вашей инструкции, в ipset появились все адреса, но ошибка No Route не ушла. 
Пробовал на разных версиях Kvas, с разными протоколами (ss и vless) - результат один. 
Вроде наличия ip адреса ipset должно быть достаточно?
Подскажите, пожалуйста, что еще нужно проверить/сделать?

**Comment by GhostRooter0953** [comment]
1. Как называется список создаваемый KVAS-ом? Покажи вывод:

```
~# ipset list -n | grep -vE '(NDM|UPNP)'
```

2. К каким гс подключаешься? В родительской репо по умолчанию только списки для RU-EU и бонусом Дубайск с Сингапуром.

3. Покажи вывод:
```
~# ipset list unblock | wc -l
```
и
```
~# kvas show | grep dis
```

**Comment by mist4keXD** [comment]
1.
`~ # ipset list -n | grep -vE '(NDM|UPNP)'
unblock
kvas_ipset`

2.
Ru

3.
`~ # ipset list unblock | wc -l
1502`

`~ # kvas show | grep dis
cdn.discordapp.com
dis.gd
discord-activities.com
discord.co
discord.com
discord.design
discord.dev
discord.gg
discord.gift
discord.gifts
discord.media
discord.new
discord.store
discord.tools
discordactivities.com
discordapp.com
discordapp.net
discordcdn.com
discordmerch.com
discordpartygames.com
discordsays.com
discordsez.com
discordstatus.com
stable.dl2.discordapp.net`

**Comment by GhostRooter0953** [comment]
А теперь вывод:

```bash
~# iptables-save | grep -vE '(NDM|UPNP)' | grep match-set
```

**Comment by mist4keXD** [comment]
> ~ # iptables-save | grep -vE '(NDM|UPNP)' | grep match-set
> -A PREROUTING -i br0 -p tcp -m set --match-set kvas_ipset dst -j REDIRECT --to-ports 1181
> -A PREROUTING -i br0 -p udp -m set --match-set kvas_ipset dst -j REDIRECT --to-ports 1181

**Comment by GhostRooter0953** [comment]
> > ~ # iptables-save | grep -vE '(NDM|UPNP)' | grep match-set
> > -A PREROUTING -i br0 -p tcp -m set --match-set kvas_ipset dst -j REDIRECT --to-ports 1181
> > -A PREROUTING -i br0 -p udp -m set --match-set kvas_ipset dst -j REDIRECT --to-ports 1181

Вот и ответ на вопрос.
У тебя список, который скрипт КВАСА генерирует, называется `kvas_ipset`.
Тебе нужно мой скрипт запускать с аргументом в виде имени списка `./kvas-ipset-adder.sh kvas_ipset`
Это я подчёркивал [тут](https://github.com/GhostRooter0953/discord-voice-ips#:~:text=./ipset%2Dadder.sh%20list%20%3Cip_list_name%3E).

**Comment by GhostRooter0953** [comment]
Можешь также удалить лишнюю цепочку:
```
~# ipset destroy unblock
```
Ну и cron задания почистить.

**Comment by mist4keXD** [comment]
Сейчас попробую. Я видел что такая возможность есть, но не думал что надо именно в ipset кваса пихать.

**Comment by GhostRooter0953** [comment]
> может что опять не так делаю.. но все еще no route
> 
> ```
> /opt/tmp/discord-ips-kvas-adder-master # ipset list kvas_ipset | wc -l
> 203
> /opt/tmp/discord-ips-kvas-adder-master # ./kvas-ipset-adder.sh kvas_ipset
> Скачивание https://github.com/GhostRooter0953/discord-voice-ips/archive/refs/heads/light.zip...
> Распаковка /opt/tmp/light.zip в /opt/tmp...
> Выдача прав на выполнение скриптов...
> Задания на авто-импорт списков в IPset уже существуют в crontab (полночь и при перезагрузке)
> Импортируем списки в IPset лист сейчас? (y/n): y
> Запуск импорта...
> 
> Запущен режим list. Используем IPset лист: kvas_ipset
> Генерируем списки в формате IPset из:
>  - ./main_domains/discord-main-ip-list
>  - ./voice_domains/discord-voice-ip-list
> Работаем дальше...
> Загружено 1459 IP адреса(ов) в IPset лист kvas_ipset
> Приехали
> /opt/tmp/discord-ips-kvas-adder-master # ipset list kvas_ipset | wc -l
> 1662
> /opt/tmp/discord-ips-kvas-adder-master # iptables-save | grep -vE '(NDM|UPNP)' | grep match-set
> -A PREROUTING -i br0 -m set --match-set kvas_ipset dst -j VPNREDIR
> -A VPNREDIR -m set ! --match-set kvas_ipset dst -j RETURN
> ```

У тебя в качестве туннеля что используется? Какой протокол?

**Comment by mist4keXD** [comment]
попробовал с ss и vless

**Comment by GhostRooter0953** [comment]
> попробовал с ss и vless

Ставь амнезию и проблем не будет.

**Comment by GhostRooter0953** [comment]
> > попробовал с ss и vless
> 
> Ставь амнезию и проблем не будет.

Ну или wg

**Comment by GhostRooter0953** [comment]
Я не тестил vless, но с соксами не работает.

**Comment by mist4keXD** [comment]
так проблема в туннеле? Как это работает?
Амнезия не удобна для меня.

**Comment by mist4keXD** [comment]
> с соксами не работает.

Печаль, ладно, спасибо в любом случае!

**Comment by GhostRooter0953** [comment]
> так проблема в туннеле? Как это работает? Амнезия не удобна для меня.

Я говорю не о клиенте, а о сервере. На стороне сервера поднимаешь либо wireguard, либо amnezia wireguard. 
На стороне роутера поднимаешь клиент wg. Далее 'подключаешь' КВАС к этому клиенту через `kvas vpn set` и готово.

**Comment by GhostRooter0953** [comment]
[Вот как это](https://docs.amnezia.org/ru/documentation/instructions/keenetic-os-awg/) делается в нативном `keenetic`.

**Comment by GhostRooter0953** [comment]
> Наверное стоит в описании упомянуть неработоспособность с соксом 

Так по итогу всё получилось?

> и то, что ip нужно добавлять в kvas_ipset.

Ну, КВАС по стоку создаёт список с [именем unblock](https://github.com/qzeleza/kvas/blob/main/HISTORY.md#:~:text=%D0%B8%D0%BC%D0%B5%D0%BD%D0%B8%20ipset%20%D1%82%D0%B0%D0%B1%D0%BB%D0%B8%D1%86%D1%8B-,unblock,-%D0%BD%D0%B0%20%D1%84%D0%B8%D1%80%D0%BC%D0%B5%D0%BD%D0%BD%D0%BE%D0%B5%20%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5). Поэтому мои скрипты его и используют, но на такие случаи я предусмотрел опцию по использованию кастомного имени и в своей доке уже [отразил](https://github.com/GhostRooter0953/discord-ips-kvas-adder#:~:text=list%20%3C%D0%B8%D0%BC%D1%8F%3E%20%E2%80%94%20%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%20%D1%83%D0%BA%D0%B0%D0%B7%D0%B0%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE%20%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B0%20IPset).

**Comment by mist4keXD** [comment]
> Ну, КВАС по стоку (в актуальной версии) создаёт список с именем unblock

У меня последняя бета как раз таки создает kvas_ipset.
![image](https://github.com/user-attachments/assets/15db3eda-87b6-4e68-bee0-639b0522063c)

> Так по итогу всё получилось?

С соксом не получилось. Амнезию пока не ставил, там надо и роутер обновлять на тестовую ветку и амнезии доступ на сервак выдавать... 
Пока пытаюсь обойтись без амнезии крч.
